const expensesCategories = [
  'Food products',
  'Cafes and restaurants',
  'Coffee and fastfood',
  'Clothes',
  'Transport',
  'Health',
  'Entertainment',
  'Education',
  'Home services',
  'Taxes',
  'Car',
  'Insurance',
  'Other',
];